name: CompatHelper
on:
  push:
    branches:
      - master
      - dev
    paths:
      - "**Project.toml"
  pull_request:
    paths:
      - "**Project.toml"
  schedule:
    - cron: 12 20 * * *
  workflow_dispatch:

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Install CompatHelper
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: Run CompatHelper
        run: julia -e 'using CompatHelper; CompatHelper.main()'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
