name: CompatHelper
on:
  push:
    branches:
      - master
      - dev
    paths:
      - "**Project.toml"
  pull_request:
    paths:
      - "**Project.toml"
  schedule:
    - cron: 12 20 * * *
  workflow_dispatch:

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/compathelper-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
